language: cpp

compiler:
  - g++

git:
  submodules: false

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - git submodule update --init --recursive

install:
  - sudo apt-get install -yqq g++-4.8 libevent-dev valgrind libboost-dev
  - export CXX="g++-4.8"

script: mkdir build && cd build && cmake .. && make && ./test/test &&
    valgrind --leak-check=full --error-exitcode=1 ./test/test
